name="Inba"
age=13
weight=93.0
student=True
print(name)
print(age)
print(weight)
print(student)
print(type(name))
print(type(age))
print(type(weight))
print(type(student))
age=str(age)
weight=int(weight)
print(age)
print(weight)
print(type(age))
print(type(weight))
