import turtle

turtle.bgcolor("blue")
turtle.fillcolor("red")
turtle.begin_fill()
turtle.forward(300)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(300)
turtle.right(90)
turtle.forward(150)
turtle.end_fill()

turtle.penup()
turtle.left(90)
turtle.forward(100)
turtle.pendown()

turtle.begin_fill()
turtle.forward(150)
turtle.right(120)
turtle.forward(50)
turtle.right(60)
turtle.forward(100)
turtle.right(60)
turtle.forward(50)
turtle.right(120)
turtle.end_fill()
