import turtle

turtle.bgcolor("blue")
turtle.fillcolor("red")
turtle.begin_fill()
turtle.forward(150)
turtle.left(120)
turtle.forward(100)
turtle.left(60)
turtle.forward(150)
turtle.left(120)
turtle.forward(100)
turtle.left(60)
turtle.end_fill()

turtle.penup()
turtle.right(90)
turtle.forward(100)
turtle.pendown()

turtle.forward(100)
turtle.back(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.back(100)
turtle.penup()
turtle.right(90)
turtle.forward(10)
turtle.left(90)
turtle.pendown()
turtle.forward(50)
turtle.penup()
turtle.forward(45)
turtle.pendown()
turtle.forward(5)
turtle.left(180)
turtle.penup()
turtle.forward(105)
turtle.pendown()
turtle.left(90)
turtle.forward(25)
turtle.back(125)
